### ISSUE TITLE
Peer Code review comments

### ISSUE THREAD

**Issue by idungstanley** [acolombo1/Portfolio#4]
- Set the titles of the frameworks to the same baseline in the about me section.
- Format buttons according to hover action in Figma templates.
- Add semantic tags for better structure of the code: footer, main, and aside (for social media icons).
-  Aligning the main cards to fit the Figma templates
- Add some padding to the main logo, so the transitioning can be less sensible.
- Adjust logo animation on mobile view.

**Comment by acolombo1** [comment]
Set the titles of the frameworks to the same baseline in the about me section. --> DONE!
Format buttons according to hover action in Figma templates. --> I will do it later if asked to, I like my design.
Add semantic tags for better structure of the code: footer, main, and aside (for social media icons). --> footer added; main and aside I leave them for my next design.
Aligning the main cards to fit the Figma templates. --> I will do it later if asked to, I like my design.
Add some padding to the main logo, so the transitioning can be less sensible. --> Can't resolve the issue, maybe it's a browser glitch, will keep on trying.
Adjust logo animation on mobile view. --> DONE!

**Comment by acolombo1** [comment]
( Add some padding to the main logo, so the transitioning can be less sensible. --> Can't resolve the issue, maybe it's a browser glitch, will keep on trying.) --> Got it now, maybe it's working better
